apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms2-deployment
  labels:
    component: ms2
spec:
  replicas: 1
  selector:
    matchLabels:
        component: ms2
  template:
    metadata:
      labels:
        component: ms2
    spec:
      containers:
      - name: ms2
        image: sannaman/ms2
        ports:
        - containerPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: ms2
spec:
  type: ClusterIP
  ports:
      - port: 9092
        targetPort: 9092
#       nodePort: 31592
  selector: 
      component: ms2